# Generated by Django 3.2.4 on 2022-07-25 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('testimonial_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('testimonial_title', models.CharField(max_length=100)),
                ('testimonial_date', models.DateTimeField()),
                ('testimonial_description', models.CharField(max_length=1000)),
                ('testimonial_count', models.IntegerField()),
            ],
        ),
    ]
