# Generated by Django 3.2.4 on 2022-07-25 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='testimonial_count',
            new_name='thanks_count',
        ),
    ]
